lib: [
  "_build/install/default/lib/network_manager/META"
  "_build/install/default/lib/network_manager/dispatcher.ml"
  "_build/install/default/lib/network_manager/dune-package"
  "_build/install/default/lib/network_manager/entrypoint.ml"
  "_build/install/default/lib/network_manager/network.ml"
  "_build/install/default/lib/network_manager/network_manager.a"
  "_build/install/default/lib/network_manager/network_manager.cma"
  "_build/install/default/lib/network_manager/network_manager.cmi"
  "_build/install/default/lib/network_manager/network_manager.cmt"
  "_build/install/default/lib/network_manager/network_manager.cmx"
  "_build/install/default/lib/network_manager/network_manager.cmxa"
  "_build/install/default/lib/network_manager/network_manager.ml"
  "_build/install/default/lib/network_manager/network_manager__Dispatcher.cmi"
  "_build/install/default/lib/network_manager/network_manager__Dispatcher.cmt"
  "_build/install/default/lib/network_manager/network_manager__Dispatcher.cmx"
  "_build/install/default/lib/network_manager/network_manager__Entrypoint.cmi"
  "_build/install/default/lib/network_manager/network_manager__Entrypoint.cmt"
  "_build/install/default/lib/network_manager/network_manager__Entrypoint.cmx"
  "_build/install/default/lib/network_manager/network_manager__Network.cmi"
  "_build/install/default/lib/network_manager/network_manager__Network.cmt"
  "_build/install/default/lib/network_manager/network_manager__Network.cmx"
  "_build/install/default/lib/network_manager/network_manager__Serialize.cmi"
  "_build/install/default/lib/network_manager/network_manager__Serialize.cmt"
  "_build/install/default/lib/network_manager/network_manager__Serialize.cmx"
  "_build/install/default/lib/network_manager/opam"
  "_build/install/default/lib/network_manager/serialize.ml"
]
libexec: [
  "_build/install/default/lib/network_manager/network_manager.cmxs"
]
bin: [
  "_build/install/default/bin/network_manager"
]
